/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddFavouriteSongsModel
 */
public class AddFavouriteSongsModelTest {
    private final AddFavouriteSongsModel model = new AddFavouriteSongsModel();

    /**
     * Model tests for AddFavouriteSongsModel
     */
    @Test
    public void testAddFavouriteSongsModel() {
        // TODO: test AddFavouriteSongsModel
    }

    /**
     * Test the property 'songId'
     */
    @Test
    public void songIdTest() {
        // TODO: test songId
    }

}
