/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddPlaylistModel
 */
public class AddPlaylistModelTest {
    private final AddPlaylistModel model = new AddPlaylistModel();

    /**
     * Model tests for AddPlaylistModel
     */
    @Test
    public void testAddPlaylistModel() {
        // TODO: test AddPlaylistModel
    }

    /**
     * Test the property 'playListName'
     */
    @Test
    public void playListNameTest() {
        // TODO: test playListName
    }

    /**
     * Test the property 'songId'
     */
    @Test
    public void songIdTest() {
        // TODO: test songId
    }

}
