/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CustomAttributeData;
import org.openapitools.client.model.MethodInfo;
import org.openapitools.client.model.Module;
import org.openapitools.client.model.SecurityRuleSet;
import org.openapitools.client.model.Type;
import org.openapitools.client.model.TypeInfo;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Assembly
 */
public class AssemblyTest {
    private final Assembly model = new Assembly();

    /**
     * Model tests for Assembly
     */
    @Test
    public void testAssembly() {
        // TODO: test Assembly
    }

    /**
     * Test the property 'definedTypes'
     */
    @Test
    public void definedTypesTest() {
        // TODO: test definedTypes
    }

    /**
     * Test the property 'exportedTypes'
     */
    @Test
    public void exportedTypesTest() {
        // TODO: test exportedTypes
    }

    /**
     * Test the property 'codeBase'
     */
    @Test
    public void codeBaseTest() {
        // TODO: test codeBase
    }

    /**
     * Test the property 'entryPoint'
     */
    @Test
    public void entryPointTest() {
        // TODO: test entryPoint
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'imageRuntimeVersion'
     */
    @Test
    public void imageRuntimeVersionTest() {
        // TODO: test imageRuntimeVersion
    }

    /**
     * Test the property 'isDynamic'
     */
    @Test
    public void isDynamicTest() {
        // TODO: test isDynamic
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'reflectionOnly'
     */
    @Test
    public void reflectionOnlyTest() {
        // TODO: test reflectionOnly
    }

    /**
     * Test the property 'isCollectible'
     */
    @Test
    public void isCollectibleTest() {
        // TODO: test isCollectible
    }

    /**
     * Test the property 'isFullyTrusted'
     */
    @Test
    public void isFullyTrustedTest() {
        // TODO: test isFullyTrusted
    }

    /**
     * Test the property 'customAttributes'
     */
    @Test
    public void customAttributesTest() {
        // TODO: test customAttributes
    }

    /**
     * Test the property 'escapedCodeBase'
     */
    @Test
    public void escapedCodeBaseTest() {
        // TODO: test escapedCodeBase
    }

    /**
     * Test the property 'manifestModule'
     */
    @Test
    public void manifestModuleTest() {
        // TODO: test manifestModule
    }

    /**
     * Test the property 'modules'
     */
    @Test
    public void modulesTest() {
        // TODO: test modules
    }

    /**
     * Test the property 'globalAssemblyCache'
     */
    @Test
    public void globalAssemblyCacheTest() {
        // TODO: test globalAssemblyCache
    }

    /**
     * Test the property 'hostContext'
     */
    @Test
    public void hostContextTest() {
        // TODO: test hostContext
    }

    /**
     * Test the property 'securityRuleSet'
     */
    @Test
    public void securityRuleSetTest() {
        // TODO: test securityRuleSet
    }

}
