/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateRequestModel
 */
public class CreateRequestModelTest {
    private final CreateRequestModel model = new CreateRequestModel();

    /**
     * Model tests for CreateRequestModel
     */
    @Test
    public void testCreateRequestModel() {
        // TODO: test CreateRequestModel
    }

    /**
     * Test the property 'requestToUserId'
     */
    @Test
    public void requestToUserIdTest() {
        // TODO: test requestToUserId
    }

}
