/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.CustomAttributeTypedArgument;
import org.openapitools.client.model.MemberInfo;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CustomAttributeNamedArgument
 */
public class CustomAttributeNamedArgumentTest {
    private final CustomAttributeNamedArgument model = new CustomAttributeNamedArgument();

    /**
     * Model tests for CustomAttributeNamedArgument
     */
    @Test
    public void testCustomAttributeNamedArgument() {
        // TODO: test CustomAttributeNamedArgument
    }

    /**
     * Test the property 'memberInfo'
     */
    @Test
    public void memberInfoTest() {
        // TODO: test memberInfo
    }

    /**
     * Test the property 'typedValue'
     */
    @Test
    public void typedValueTest() {
        // TODO: test typedValue
    }

    /**
     * Test the property 'memberName'
     */
    @Test
    public void memberNameTest() {
        // TODO: test memberName
    }

    /**
     * Test the property 'isField'
     */
    @Test
    public void isFieldTest() {
        // TODO: test isField
    }

}
