/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CustomPaymentRequestModel
 */
public class CustomPaymentRequestModelTest {
    private final CustomPaymentRequestModel model = new CustomPaymentRequestModel();

    /**
     * Model tests for CustomPaymentRequestModel
     */
    @Test
    public void testCustomPaymentRequestModel() {
        // TODO: test CustomPaymentRequestModel
    }

    /**
     * Test the property 'applicantEmail'
     */
    @Test
    public void applicantEmailTest() {
        // TODO: test applicantEmail
    }

    /**
     * Test the property 'subscriptionPlan'
     */
    @Test
    public void subscriptionPlanTest() {
        // TODO: test subscriptionPlan
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'noOfUsers'
     */
    @Test
    public void noOfUsersTest() {
        // TODO: test noOfUsers
    }

}
