/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.MethodBase;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Exception
 */
public class ExceptionTest {
    private final Exception model = new Exception();

    /**
     * Model tests for Exception
     */
    @Test
    public void testException() {
        // TODO: test Exception
    }

    /**
     * Test the property 'targetSite'
     */
    @Test
    public void targetSiteTest() {
        // TODO: test targetSite
    }

    /**
     * Test the property 'stackTrace'
     */
    @Test
    public void stackTraceTest() {
        // TODO: test stackTrace
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'innerException'
     */
    @Test
    public void innerExceptionTest() {
        // TODO: test innerException
    }

    /**
     * Test the property 'helpLink'
     */
    @Test
    public void helpLinkTest() {
        // TODO: test helpLink
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'hResult'
     */
    @Test
    public void hResultTest() {
        // TODO: test hResult
    }

}
