/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CustomAttributeData;
import org.openapitools.client.model.FieldAttributes;
import org.openapitools.client.model.MemberTypes;
import org.openapitools.client.model.Module;
import org.openapitools.client.model.RuntimeFieldHandle;
import org.openapitools.client.model.Type;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FieldInfo
 */
public class FieldInfoTest {
    private final FieldInfo model = new FieldInfo();

    /**
     * Model tests for FieldInfo
     */
    @Test
    public void testFieldInfo() {
        // TODO: test FieldInfo
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'declaringType'
     */
    @Test
    public void declaringTypeTest() {
        // TODO: test declaringType
    }

    /**
     * Test the property 'reflectedType'
     */
    @Test
    public void reflectedTypeTest() {
        // TODO: test reflectedType
    }

    /**
     * Test the property 'module'
     */
    @Test
    public void moduleTest() {
        // TODO: test module
    }

    /**
     * Test the property 'customAttributes'
     */
    @Test
    public void customAttributesTest() {
        // TODO: test customAttributes
    }

    /**
     * Test the property 'isCollectible'
     */
    @Test
    public void isCollectibleTest() {
        // TODO: test isCollectible
    }

    /**
     * Test the property 'metadataToken'
     */
    @Test
    public void metadataTokenTest() {
        // TODO: test metadataToken
    }

    /**
     * Test the property 'memberType'
     */
    @Test
    public void memberTypeTest() {
        // TODO: test memberType
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'fieldType'
     */
    @Test
    public void fieldTypeTest() {
        // TODO: test fieldType
    }

    /**
     * Test the property 'isInitOnly'
     */
    @Test
    public void isInitOnlyTest() {
        // TODO: test isInitOnly
    }

    /**
     * Test the property 'isLiteral'
     */
    @Test
    public void isLiteralTest() {
        // TODO: test isLiteral
    }

    /**
     * Test the property 'isNotSerialized'
     */
    @Test
    public void isNotSerializedTest() {
        // TODO: test isNotSerialized
    }

    /**
     * Test the property 'isPinvokeImpl'
     */
    @Test
    public void isPinvokeImplTest() {
        // TODO: test isPinvokeImpl
    }

    /**
     * Test the property 'isSpecialName'
     */
    @Test
    public void isSpecialNameTest() {
        // TODO: test isSpecialName
    }

    /**
     * Test the property 'isStatic'
     */
    @Test
    public void isStaticTest() {
        // TODO: test isStatic
    }

    /**
     * Test the property 'isAssembly'
     */
    @Test
    public void isAssemblyTest() {
        // TODO: test isAssembly
    }

    /**
     * Test the property 'isFamily'
     */
    @Test
    public void isFamilyTest() {
        // TODO: test isFamily
    }

    /**
     * Test the property 'isFamilyAndAssembly'
     */
    @Test
    public void isFamilyAndAssemblyTest() {
        // TODO: test isFamilyAndAssembly
    }

    /**
     * Test the property 'isFamilyOrAssembly'
     */
    @Test
    public void isFamilyOrAssemblyTest() {
        // TODO: test isFamilyOrAssembly
    }

    /**
     * Test the property 'isPrivate'
     */
    @Test
    public void isPrivateTest() {
        // TODO: test isPrivate
    }

    /**
     * Test the property 'isPublic'
     */
    @Test
    public void isPublicTest() {
        // TODO: test isPublic
    }

    /**
     * Test the property 'isSecurityCritical'
     */
    @Test
    public void isSecurityCriticalTest() {
        // TODO: test isSecurityCritical
    }

    /**
     * Test the property 'isSecuritySafeCritical'
     */
    @Test
    public void isSecuritySafeCriticalTest() {
        // TODO: test isSecuritySafeCritical
    }

    /**
     * Test the property 'isSecurityTransparent'
     */
    @Test
    public void isSecurityTransparentTest() {
        // TODO: test isSecurityTransparent
    }

    /**
     * Test the property 'fieldHandle'
     */
    @Test
    public void fieldHandleTest() {
        // TODO: test fieldHandle
    }

}
