/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetGrearDetailsModel
 */
public class GetGrearDetailsModelTest {
    private final GetGrearDetailsModel model = new GetGrearDetailsModel();

    /**
     * Model tests for GetGrearDetailsModel
     */
    @Test
    public void testGetGrearDetailsModel() {
        // TODO: test GetGrearDetailsModel
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'brandName'
     */
    @Test
    public void brandNameTest() {
        // TODO: test brandName
    }

    /**
     * Test the property 'brandId'
     */
    @Test
    public void brandIdTest() {
        // TODO: test brandId
    }

    /**
     * Test the property 'gearName'
     */
    @Test
    public void gearNameTest() {
        // TODO: test gearName
    }

    /**
     * Test the property 'gearPhoto'
     */
    @Test
    public void gearPhotoTest() {
        // TODO: test gearPhoto
    }

    /**
     * Test the property 'gearBrandId'
     */
    @Test
    public void gearBrandIdTest() {
        // TODO: test gearBrandId
    }

    /**
     * Test the property 'gearDesc'
     */
    @Test
    public void gearDescTest() {
        // TODO: test gearDesc
    }

}
