/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetMyChallengeModel
 */
public class GetMyChallengeModelTest {
    private final GetMyChallengeModel model = new GetMyChallengeModel();

    /**
     * Model tests for GetMyChallengeModel
     */
    @Test
    public void testGetMyChallengeModel() {
        // TODO: test GetMyChallengeModel
    }

    /**
     * Test the property 'challengeId'
     */
    @Test
    public void challengeIdTest() {
        // TODO: test challengeId
    }

    /**
     * Test the property 'challengeName'
     */
    @Test
    public void challengeNameTest() {
        // TODO: test challengeName
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'distanceMeasurementId'
     */
    @Test
    public void distanceMeasurementIdTest() {
        // TODO: test distanceMeasurementId
    }

    /**
     * Test the property 'challengeStartTime'
     */
    @Test
    public void challengeStartTimeTest() {
        // TODO: test challengeStartTime
    }

    /**
     * Test the property 'challengeEndTime'
     */
    @Test
    public void challengeEndTimeTest() {
        // TODO: test challengeEndTime
    }

    /**
     * Test the property 'challengeDate'
     */
    @Test
    public void challengeDateTest() {
        // TODO: test challengeDate
    }

    /**
     * Test the property 'themesId'
     */
    @Test
    public void themesIdTest() {
        // TODO: test themesId
    }

    /**
     * Test the property 'themeName'
     */
    @Test
    public void themeNameTest() {
        // TODO: test themeName
    }

    /**
     * Test the property 'challengeStatus'
     */
    @Test
    public void challengeStatusTest() {
        // TODO: test challengeStatus
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'remainingDate'
     */
    @Test
    public void remainingDateTest() {
        // TODO: test remainingDate
    }

    /**
     * Test the property 'totalParticipantsCount'
     */
    @Test
    public void totalParticipantsCountTest() {
        // TODO: test totalParticipantsCount
    }

}
