/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetUserActivityModel
 */
public class GetUserActivityModelTest {
    private final GetUserActivityModel model = new GetUserActivityModel();

    /**
     * Model tests for GetUserActivityModel
     */
    @Test
    public void testGetUserActivityModel() {
        // TODO: test GetUserActivityModel
    }

    /**
     * Test the property 'pace'
     */
    @Test
    public void paceTest() {
        // TODO: test pace
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'calories'
     */
    @Test
    public void caloriesTest() {
        // TODO: test calories
    }

    /**
     * Test the property 'elevationGain'
     */
    @Test
    public void elevationGainTest() {
        // TODO: test elevationGain
    }

    /**
     * Test the property 'cadence'
     */
    @Test
    public void cadenceTest() {
        // TODO: test cadence
    }

    /**
     * Test the property 'longitude'
     */
    @Test
    public void longitudeTest() {
        // TODO: test longitude
    }

    /**
     * Test the property 'latitude'
     */
    @Test
    public void latitudeTest() {
        // TODO: test latitude
    }

}
