/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetVideoDetailsModel
 */
public class GetVideoDetailsModelTest {
    private final GetVideoDetailsModel model = new GetVideoDetailsModel();

    /**
     * Model tests for GetVideoDetailsModel
     */
    @Test
    public void testGetVideoDetailsModel() {
        // TODO: test GetVideoDetailsModel
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'categoryName'
     */
    @Test
    public void categoryNameTest() {
        // TODO: test categoryName
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'videoFilePath'
     */
    @Test
    public void videoFilePathTest() {
        // TODO: test videoFilePath
    }

    /**
     * Test the property 'videoImagePath'
     */
    @Test
    public void videoImagePathTest() {
        // TODO: test videoImagePath
    }

}
