/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GroupAdminModel
 */
public class GroupAdminModelTest {
    private final GroupAdminModel model = new GroupAdminModel();

    /**
     * Model tests for GroupAdminModel
     */
    @Test
    public void testGroupAdminModel() {
        // TODO: test GroupAdminModel
    }

    /**
     * Test the property 'activeUsers'
     */
    @Test
    public void activeUsersTest() {
        // TODO: test activeUsers
    }

    /**
     * Test the property 'unActiveUsers'
     */
    @Test
    public void unActiveUsersTest() {
        // TODO: test unActiveUsers
    }

    /**
     * Test the property 'totalUsers'
     */
    @Test
    public void totalUsersTest() {
        // TODO: test totalUsers
    }

    /**
     * Test the property 'maleUsers'
     */
    @Test
    public void maleUsersTest() {
        // TODO: test maleUsers
    }

    /**
     * Test the property 'femaleUsers'
     */
    @Test
    public void femaleUsersTest() {
        // TODO: test femaleUsers
    }

    /**
     * Test the property 'ageUsersBetween18to40'
     */
    @Test
    public void ageUsersBetween18to40Test() {
        // TODO: test ageUsersBetween18to40
    }

    /**
     * Test the property 'ageUsersBetween40to70'
     */
    @Test
    public void ageUsersBetween40to70Test() {
        // TODO: test ageUsersBetween40to70
    }

    /**
     * Test the property 'ageUsersBetween70to100'
     */
    @Test
    public void ageUsersBetween70to100Test() {
        // TODO: test ageUsersBetween70to100
    }

}
