/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CustomAttributeData;
import org.openapitools.client.model.MemberTypes;
import org.openapitools.client.model.Module;
import org.openapitools.client.model.Type;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MemberInfo
 */
public class MemberInfoTest {
    private final MemberInfo model = new MemberInfo();

    /**
     * Model tests for MemberInfo
     */
    @Test
    public void testMemberInfo() {
        // TODO: test MemberInfo
    }

    /**
     * Test the property 'memberType'
     */
    @Test
    public void memberTypeTest() {
        // TODO: test memberType
    }

    /**
     * Test the property 'declaringType'
     */
    @Test
    public void declaringTypeTest() {
        // TODO: test declaringType
    }

    /**
     * Test the property 'reflectedType'
     */
    @Test
    public void reflectedTypeTest() {
        // TODO: test reflectedType
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'module'
     */
    @Test
    public void moduleTest() {
        // TODO: test module
    }

    /**
     * Test the property 'customAttributes'
     */
    @Test
    public void customAttributesTest() {
        // TODO: test customAttributes
    }

    /**
     * Test the property 'isCollectible'
     */
    @Test
    public void isCollectibleTest() {
        // TODO: test isCollectible
    }

    /**
     * Test the property 'metadataToken'
     */
    @Test
    public void metadataTokenTest() {
        // TODO: test metadataToken
    }

}
