/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CallingConventions;
import org.openapitools.client.model.CustomAttributeData;
import org.openapitools.client.model.MemberTypes;
import org.openapitools.client.model.MethodAttributes;
import org.openapitools.client.model.MethodImplAttributes;
import org.openapitools.client.model.Module;
import org.openapitools.client.model.ParameterInfo;
import org.openapitools.client.model.RuntimeMethodHandle;
import org.openapitools.client.model.Type;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MethodInfo
 */
public class MethodInfoTest {
    private final MethodInfo model = new MethodInfo();

    /**
     * Model tests for MethodInfo
     */
    @Test
    public void testMethodInfo() {
        // TODO: test MethodInfo
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'declaringType'
     */
    @Test
    public void declaringTypeTest() {
        // TODO: test declaringType
    }

    /**
     * Test the property 'reflectedType'
     */
    @Test
    public void reflectedTypeTest() {
        // TODO: test reflectedType
    }

    /**
     * Test the property 'module'
     */
    @Test
    public void moduleTest() {
        // TODO: test module
    }

    /**
     * Test the property 'customAttributes'
     */
    @Test
    public void customAttributesTest() {
        // TODO: test customAttributes
    }

    /**
     * Test the property 'isCollectible'
     */
    @Test
    public void isCollectibleTest() {
        // TODO: test isCollectible
    }

    /**
     * Test the property 'metadataToken'
     */
    @Test
    public void metadataTokenTest() {
        // TODO: test metadataToken
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'methodImplementationFlags'
     */
    @Test
    public void methodImplementationFlagsTest() {
        // TODO: test methodImplementationFlags
    }

    /**
     * Test the property 'callingConvention'
     */
    @Test
    public void callingConventionTest() {
        // TODO: test callingConvention
    }

    /**
     * Test the property 'isAbstract'
     */
    @Test
    public void isAbstractTest() {
        // TODO: test isAbstract
    }

    /**
     * Test the property 'isConstructor'
     */
    @Test
    public void isConstructorTest() {
        // TODO: test isConstructor
    }

    /**
     * Test the property 'isFinal'
     */
    @Test
    public void isFinalTest() {
        // TODO: test isFinal
    }

    /**
     * Test the property 'isHideBySig'
     */
    @Test
    public void isHideBySigTest() {
        // TODO: test isHideBySig
    }

    /**
     * Test the property 'isSpecialName'
     */
    @Test
    public void isSpecialNameTest() {
        // TODO: test isSpecialName
    }

    /**
     * Test the property 'isStatic'
     */
    @Test
    public void isStaticTest() {
        // TODO: test isStatic
    }

    /**
     * Test the property 'isVirtual'
     */
    @Test
    public void isVirtualTest() {
        // TODO: test isVirtual
    }

    /**
     * Test the property 'isAssembly'
     */
    @Test
    public void isAssemblyTest() {
        // TODO: test isAssembly
    }

    /**
     * Test the property 'isFamily'
     */
    @Test
    public void isFamilyTest() {
        // TODO: test isFamily
    }

    /**
     * Test the property 'isFamilyAndAssembly'
     */
    @Test
    public void isFamilyAndAssemblyTest() {
        // TODO: test isFamilyAndAssembly
    }

    /**
     * Test the property 'isFamilyOrAssembly'
     */
    @Test
    public void isFamilyOrAssemblyTest() {
        // TODO: test isFamilyOrAssembly
    }

    /**
     * Test the property 'isPrivate'
     */
    @Test
    public void isPrivateTest() {
        // TODO: test isPrivate
    }

    /**
     * Test the property 'isPublic'
     */
    @Test
    public void isPublicTest() {
        // TODO: test isPublic
    }

    /**
     * Test the property 'isConstructedGenericMethod'
     */
    @Test
    public void isConstructedGenericMethodTest() {
        // TODO: test isConstructedGenericMethod
    }

    /**
     * Test the property 'isGenericMethod'
     */
    @Test
    public void isGenericMethodTest() {
        // TODO: test isGenericMethod
    }

    /**
     * Test the property 'isGenericMethodDefinition'
     */
    @Test
    public void isGenericMethodDefinitionTest() {
        // TODO: test isGenericMethodDefinition
    }

    /**
     * Test the property 'containsGenericParameters'
     */
    @Test
    public void containsGenericParametersTest() {
        // TODO: test containsGenericParameters
    }

    /**
     * Test the property 'methodHandle'
     */
    @Test
    public void methodHandleTest() {
        // TODO: test methodHandle
    }

    /**
     * Test the property 'isSecurityCritical'
     */
    @Test
    public void isSecurityCriticalTest() {
        // TODO: test isSecurityCritical
    }

    /**
     * Test the property 'isSecuritySafeCritical'
     */
    @Test
    public void isSecuritySafeCriticalTest() {
        // TODO: test isSecuritySafeCritical
    }

    /**
     * Test the property 'isSecurityTransparent'
     */
    @Test
    public void isSecurityTransparentTest() {
        // TODO: test isSecurityTransparent
    }

    /**
     * Test the property 'memberType'
     */
    @Test
    public void memberTypeTest() {
        // TODO: test memberType
    }

    /**
     * Test the property 'returnParameter'
     */
    @Test
    public void returnParameterTest() {
        // TODO: test returnParameter
    }

    /**
     * Test the property 'returnType'
     */
    @Test
    public void returnTypeTest() {
        // TODO: test returnType
    }

    /**
     * Test the property 'returnTypeCustomAttributes'
     */
    @Test
    public void returnTypeCustomAttributesTest() {
        // TODO: test returnTypeCustomAttributes
    }

}
