/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.Assembly;
import org.openapitools.client.model.CustomAttributeData;
import org.openapitools.client.model.ModuleHandle;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Module
 */
public class ModuleTest {
    private final Module model = new Module();

    /**
     * Model tests for Module
     */
    @Test
    public void testModule() {
        // TODO: test Module
    }

    /**
     * Test the property 'assembly'
     */
    @Test
    public void assemblyTest() {
        // TODO: test assembly
    }

    /**
     * Test the property 'fullyQualifiedName'
     */
    @Test
    public void fullyQualifiedNameTest() {
        // TODO: test fullyQualifiedName
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'mdStreamVersion'
     */
    @Test
    public void mdStreamVersionTest() {
        // TODO: test mdStreamVersion
    }

    /**
     * Test the property 'moduleVersionId'
     */
    @Test
    public void moduleVersionIdTest() {
        // TODO: test moduleVersionId
    }

    /**
     * Test the property 'scopeName'
     */
    @Test
    public void scopeNameTest() {
        // TODO: test scopeName
    }

    /**
     * Test the property 'moduleHandle'
     */
    @Test
    public void moduleHandleTest() {
        // TODO: test moduleHandle
    }

    /**
     * Test the property 'customAttributes'
     */
    @Test
    public void customAttributesTest() {
        // TODO: test customAttributes
    }

    /**
     * Test the property 'metadataToken'
     */
    @Test
    public void metadataTokenTest() {
        // TODO: test metadataToken
    }

}
