/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CustomAttributeData;
import org.openapitools.client.model.MemberInfo;
import org.openapitools.client.model.ParameterAttributes;
import org.openapitools.client.model.Type;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ParameterInfo
 */
public class ParameterInfoTest {
    private final ParameterInfo model = new ParameterInfo();

    /**
     * Model tests for ParameterInfo
     */
    @Test
    public void testParameterInfo() {
        // TODO: test ParameterInfo
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'member'
     */
    @Test
    public void memberTest() {
        // TODO: test member
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'parameterType'
     */
    @Test
    public void parameterTypeTest() {
        // TODO: test parameterType
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'isIn'
     */
    @Test
    public void isInTest() {
        // TODO: test isIn
    }

    /**
     * Test the property 'isLcid'
     */
    @Test
    public void isLcidTest() {
        // TODO: test isLcid
    }

    /**
     * Test the property 'isOptional'
     */
    @Test
    public void isOptionalTest() {
        // TODO: test isOptional
    }

    /**
     * Test the property 'isOut'
     */
    @Test
    public void isOutTest() {
        // TODO: test isOut
    }

    /**
     * Test the property 'isRetval'
     */
    @Test
    public void isRetvalTest() {
        // TODO: test isRetval
    }

    /**
     * Test the property 'defaultValue'
     */
    @Test
    public void defaultValueTest() {
        // TODO: test defaultValue
    }

    /**
     * Test the property 'rawDefaultValue'
     */
    @Test
    public void rawDefaultValueTest() {
        // TODO: test rawDefaultValue
    }

    /**
     * Test the property 'hasDefaultValue'
     */
    @Test
    public void hasDefaultValueTest() {
        // TODO: test hasDefaultValue
    }

    /**
     * Test the property 'customAttributes'
     */
    @Test
    public void customAttributesTest() {
        // TODO: test customAttributes
    }

    /**
     * Test the property 'metadataToken'
     */
    @Test
    public void metadataTokenTest() {
        // TODO: test metadataToken
    }

}
