/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PaymentGatewayModel
 */
public class PaymentGatewayModelTest {
    private final PaymentGatewayModel model = new PaymentGatewayModel();

    /**
     * Model tests for PaymentGatewayModel
     */
    @Test
    public void testPaymentGatewayModel() {
        // TODO: test PaymentGatewayModel
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'subscriptionName'
     */
    @Test
    public void subscriptionNameTest() {
        // TODO: test subscriptionName
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'recipientEmail'
     */
    @Test
    public void recipientEmailTest() {
        // TODO: test recipientEmail
    }

}
