/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RegisterModel
 */
public class RegisterModelTest {
    private final RegisterModel model = new RegisterModel();

    /**
     * Model tests for RegisterModel
     */
    @Test
    public void testRegisterModel() {
        // TODO: test RegisterModel
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'contactNumber'
     */
    @Test
    public void contactNumberTest() {
        // TODO: test contactNumber
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'cityId'
     */
    @Test
    public void cityIdTest() {
        // TODO: test cityId
    }

    /**
     * Test the property 'provinceStateId'
     */
    @Test
    public void provinceStateIdTest() {
        // TODO: test provinceStateId
    }

    /**
     * Test the property 'countryID'
     */
    @Test
    public void countryIDTest() {
        // TODO: test countryID
    }

    /**
     * Test the property 'languageId'
     */
    @Test
    public void languageIdTest() {
        // TODO: test languageId
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'roleId'
     */
    @Test
    public void roleIdTest() {
        // TODO: test roleId
    }

}
