/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserResponseModel
 */
public class UserResponseModelTest {
    private final UserResponseModel model = new UserResponseModel();

    /**
     * Model tests for UserResponseModel
     */
    @Test
    public void testUserResponseModel() {
        // TODO: test UserResponseModel
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'contactNumber'
     */
    @Test
    public void contactNumberTest() {
        // TODO: test contactNumber
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'heightMeasurementName'
     */
    @Test
    public void heightMeasurementNameTest() {
        // TODO: test heightMeasurementName
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

    /**
     * Test the property 'weightMeasurementName'
     */
    @Test
    public void weightMeasurementNameTest() {
        // TODO: test weightMeasurementName
    }

    /**
     * Test the property 'profilePhoto'
     */
    @Test
    public void profilePhotoTest() {
        // TODO: test profilePhoto
    }

    /**
     * Test the property 'age'
     */
    @Test
    public void ageTest() {
        // TODO: test age
    }

    /**
     * Test the property 'group'
     */
    @Test
    public void groupTest() {
        // TODO: test group
    }

    /**
     * Test the property 'countryID'
     */
    @Test
    public void countryIDTest() {
        // TODO: test countryID
    }

    /**
     * Test the property 'countryName'
     */
    @Test
    public void countryNameTest() {
        // TODO: test countryName
    }

    /**
     * Test the property 'cityId'
     */
    @Test
    public void cityIdTest() {
        // TODO: test cityId
    }

    /**
     * Test the property 'cityName'
     */
    @Test
    public void cityNameTest() {
        // TODO: test cityName
    }

    /**
     * Test the property 'provinceStateId'
     */
    @Test
    public void provinceStateIdTest() {
        // TODO: test provinceStateId
    }

    /**
     * Test the property 'provinceStateName'
     */
    @Test
    public void provinceStateNameTest() {
        // TODO: test provinceStateName
    }

    /**
     * Test the property 'languageId'
     */
    @Test
    public void languageIdTest() {
        // TODO: test languageId
    }

    /**
     * Test the property 'languageName'
     */
    @Test
    public void languageNameTest() {
        // TODO: test languageName
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

}
