/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserGearModel
 */
public class UserGearModelTest {
    private final UserGearModel model = new UserGearModel();

    /**
     * Model tests for UserGearModel
     */
    @Test
    public void testUserGearModel() {
        // TODO: test UserGearModel
    }

    /**
     * Test the property 'nickname'
     */
    @Test
    public void nicknameTest() {
        // TODO: test nickname
    }

    /**
     * Test the property 'maxDistance'
     */
    @Test
    public void maxDistanceTest() {
        // TODO: test maxDistance
    }

    /**
     * Test the property 'distanceMeasurementId'
     */
    @Test
    public void distanceMeasurementIdTest() {
        // TODO: test distanceMeasurementId
    }

    /**
     * Test the property 'isRetired'
     */
    @Test
    public void isRetiredTest() {
        // TODO: test isRetired
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'gearId'
     */
    @Test
    public void gearIdTest() {
        // TODO: test gearId
    }

    /**
     * Test the property 'gearBrandId'
     */
    @Test
    public void gearBrandIdTest() {
        // TODO: test gearBrandId
    }

    /**
     * Test the property 'isWalking'
     */
    @Test
    public void isWalkingTest() {
        // TODO: test isWalking
    }

}
