/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * AddPlaylistModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-24T12:51:03.671750900+05:30[Asia/Calcutta]")
public class AddPlaylistModel implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_PLAY_LIST_NAME = "playListName";
  @SerializedName(SERIALIZED_NAME_PLAY_LIST_NAME)
  private String playListName;

  public static final String SERIALIZED_NAME_SONG_ID = "songId";
  @SerializedName(SERIALIZED_NAME_SONG_ID)
  private List<Integer> songId = null;


  public AddPlaylistModel playListName(String playListName) {
    
    this.playListName = playListName;
    return this;
  }

   /**
   * Get playListName
   * @return playListName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPlayListName() {
    return playListName;
  }


  public void setPlayListName(String playListName) {
    this.playListName = playListName;
  }


  public AddPlaylistModel songId(List<Integer> songId) {
    
    this.songId = songId;
    return this;
  }

  public AddPlaylistModel addSongIdItem(Integer songIdItem) {
    if (this.songId == null) {
      this.songId = new ArrayList<Integer>();
    }
    this.songId.add(songIdItem);
    return this;
  }

   /**
   * Get songId
   * @return songId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getSongId() {
    return songId;
  }


  public void setSongId(List<Integer> songId) {
    this.songId = songId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddPlaylistModel addPlaylistModel = (AddPlaylistModel) o;
    return Objects.equals(this.playListName, addPlaylistModel.playListName) &&
        Objects.equals(this.songId, addPlaylistModel.songId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(playListName, songId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddPlaylistModel {\n");
    sb.append("    playListName: ").append(toIndentedString(playListName)).append("\n");
    sb.append("    songId: ").append(toIndentedString(songId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

