/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * AddQueryDetailsModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-24T12:51:03.671750900+05:30[Asia/Calcutta]")
public class AddQueryDetailsModel implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_QUERY_ID = "queryId";
  @SerializedName(SERIALIZED_NAME_QUERY_ID)
  private Long queryId;

  public static final String SERIALIZED_NAME_QUERY_MESSAGE = "queryMessage";
  @SerializedName(SERIALIZED_NAME_QUERY_MESSAGE)
  private String queryMessage;

  public static final String SERIALIZED_NAME_QUERY_PHOTO_PATH = "queryPhotoPath";
  @SerializedName(SERIALIZED_NAME_QUERY_PHOTO_PATH)
  private String queryPhotoPath;


  public AddQueryDetailsModel queryId(Long queryId) {
    
    this.queryId = queryId;
    return this;
  }

   /**
   * Get queryId
   * @return queryId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getQueryId() {
    return queryId;
  }


  public void setQueryId(Long queryId) {
    this.queryId = queryId;
  }


  public AddQueryDetailsModel queryMessage(String queryMessage) {
    
    this.queryMessage = queryMessage;
    return this;
  }

   /**
   * Get queryMessage
   * @return queryMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getQueryMessage() {
    return queryMessage;
  }


  public void setQueryMessage(String queryMessage) {
    this.queryMessage = queryMessage;
  }


  public AddQueryDetailsModel queryPhotoPath(String queryPhotoPath) {
    
    this.queryPhotoPath = queryPhotoPath;
    return this;
  }

   /**
   * Get queryPhotoPath
   * @return queryPhotoPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getQueryPhotoPath() {
    return queryPhotoPath;
  }


  public void setQueryPhotoPath(String queryPhotoPath) {
    this.queryPhotoPath = queryPhotoPath;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddQueryDetailsModel addQueryDetailsModel = (AddQueryDetailsModel) o;
    return Objects.equals(this.queryId, addQueryDetailsModel.queryId) &&
        Objects.equals(this.queryMessage, addQueryDetailsModel.queryMessage) &&
        Objects.equals(this.queryPhotoPath, addQueryDetailsModel.queryPhotoPath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queryId, queryMessage, queryPhotoPath);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddQueryDetailsModel {\n");
    sb.append("    queryId: ").append(toIndentedString(queryId)).append("\n");
    sb.append("    queryMessage: ").append(toIndentedString(queryMessage)).append("\n");
    sb.append("    queryPhotoPath: ").append(toIndentedString(queryPhotoPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

