/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CallingConventions
 */
@JsonAdapter(CallingConventions.Adapter.class)
public enum CallingConventions {
  
  NUMBER_1(1),
  
  NUMBER_2(2),
  
  NUMBER_3(3),
  
  NUMBER_32(32),
  
  NUMBER_64(64);

  private Integer value;

  CallingConventions(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CallingConventions fromValue(Integer value) {
    for (CallingConventions b : CallingConventions.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CallingConventions> {
    @Override
    public void write(final JsonWriter jsonWriter, final CallingConventions enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CallingConventions read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return CallingConventions.fromValue(value);
    }
  }
}

