/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;
import java.io.Serializable;

/**
 * ChallengeUserModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-24T12:51:03.671750900+05:30[Asia/Calcutta]")
public class ChallengeUserModel implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_PACE = "pace";
  @SerializedName(SERIALIZED_NAME_PACE)
  private Double pace;

  public static final String SERIALIZED_NAME_DISTANCE = "distance";
  @SerializedName(SERIALIZED_NAME_DISTANCE)
  private Double distance;

  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  private Date time;

  public static final String SERIALIZED_NAME_CALORIES = "calories";
  @SerializedName(SERIALIZED_NAME_CALORIES)
  private Double calories;

  public static final String SERIALIZED_NAME_ELEVATION_GAIN = "elevationGain";
  @SerializedName(SERIALIZED_NAME_ELEVATION_GAIN)
  private Double elevationGain;

  public static final String SERIALIZED_NAME_CADENCE = "cadence";
  @SerializedName(SERIALIZED_NAME_CADENCE)
  private Double cadence;

  public static final String SERIALIZED_NAME_LONGITUDE = "longitude";
  @SerializedName(SERIALIZED_NAME_LONGITUDE)
  private String longitude;

  public static final String SERIALIZED_NAME_LATITUDE = "latitude";
  @SerializedName(SERIALIZED_NAME_LATITUDE)
  private String latitude;

  public static final String SERIALIZED_NAME_IS_PAUSE = "isPause";
  @SerializedName(SERIALIZED_NAME_IS_PAUSE)
  private Boolean isPause;

  public static final String SERIALIZED_NAME_IS_RUNNING_OR_STOP = "isRunningOrStop";
  @SerializedName(SERIALIZED_NAME_IS_RUNNING_OR_STOP)
  private Boolean isRunningOrStop;

  public static final String SERIALIZED_NAME_CHALLENGE_ID = "challengeId";
  @SerializedName(SERIALIZED_NAME_CHALLENGE_ID)
  private Long challengeId;


  public ChallengeUserModel pace(Double pace) {
    
    this.pace = pace;
    return this;
  }

   /**
   * Get pace
   * @return pace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getPace() {
    return pace;
  }


  public void setPace(Double pace) {
    this.pace = pace;
  }


  public ChallengeUserModel distance(Double distance) {
    
    this.distance = distance;
    return this;
  }

   /**
   * Get distance
   * @return distance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getDistance() {
    return distance;
  }


  public void setDistance(Double distance) {
    this.distance = distance;
  }


  public ChallengeUserModel time(Date time) {
    
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Date getTime() {
    return time;
  }


  public void setTime(Date time) {
    this.time = time;
  }


  public ChallengeUserModel calories(Double calories) {
    
    this.calories = calories;
    return this;
  }

   /**
   * Get calories
   * @return calories
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getCalories() {
    return calories;
  }


  public void setCalories(Double calories) {
    this.calories = calories;
  }


  public ChallengeUserModel elevationGain(Double elevationGain) {
    
    this.elevationGain = elevationGain;
    return this;
  }

   /**
   * Get elevationGain
   * @return elevationGain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getElevationGain() {
    return elevationGain;
  }


  public void setElevationGain(Double elevationGain) {
    this.elevationGain = elevationGain;
  }


  public ChallengeUserModel cadence(Double cadence) {
    
    this.cadence = cadence;
    return this;
  }

   /**
   * Get cadence
   * @return cadence
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getCadence() {
    return cadence;
  }


  public void setCadence(Double cadence) {
    this.cadence = cadence;
  }


  public ChallengeUserModel longitude(String longitude) {
    
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLongitude() {
    return longitude;
  }


  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }


  public ChallengeUserModel latitude(String latitude) {
    
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLatitude() {
    return latitude;
  }


  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }


  public ChallengeUserModel isPause(Boolean isPause) {
    
    this.isPause = isPause;
    return this;
  }

   /**
   * Get isPause
   * @return isPause
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsPause() {
    return isPause;
  }


  public void setIsPause(Boolean isPause) {
    this.isPause = isPause;
  }


  public ChallengeUserModel isRunningOrStop(Boolean isRunningOrStop) {
    
    this.isRunningOrStop = isRunningOrStop;
    return this;
  }

   /**
   * Get isRunningOrStop
   * @return isRunningOrStop
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsRunningOrStop() {
    return isRunningOrStop;
  }


  public void setIsRunningOrStop(Boolean isRunningOrStop) {
    this.isRunningOrStop = isRunningOrStop;
  }


  public ChallengeUserModel challengeId(Long challengeId) {
    
    this.challengeId = challengeId;
    return this;
  }

   /**
   * Get challengeId
   * @return challengeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getChallengeId() {
    return challengeId;
  }


  public void setChallengeId(Long challengeId) {
    this.challengeId = challengeId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChallengeUserModel challengeUserModel = (ChallengeUserModel) o;
    return Objects.equals(this.pace, challengeUserModel.pace) &&
        Objects.equals(this.distance, challengeUserModel.distance) &&
        Objects.equals(this.time, challengeUserModel.time) &&
        Objects.equals(this.calories, challengeUserModel.calories) &&
        Objects.equals(this.elevationGain, challengeUserModel.elevationGain) &&
        Objects.equals(this.cadence, challengeUserModel.cadence) &&
        Objects.equals(this.longitude, challengeUserModel.longitude) &&
        Objects.equals(this.latitude, challengeUserModel.latitude) &&
        Objects.equals(this.isPause, challengeUserModel.isPause) &&
        Objects.equals(this.isRunningOrStop, challengeUserModel.isRunningOrStop) &&
        Objects.equals(this.challengeId, challengeUserModel.challengeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pace, distance, time, calories, elevationGain, cadence, longitude, latitude, isPause, isRunningOrStop, challengeId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChallengeUserModel {\n");
    sb.append("    pace: ").append(toIndentedString(pace)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    calories: ").append(toIndentedString(calories)).append("\n");
    sb.append("    elevationGain: ").append(toIndentedString(elevationGain)).append("\n");
    sb.append("    cadence: ").append(toIndentedString(cadence)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    isPause: ").append(toIndentedString(isPause)).append("\n");
    sb.append("    isRunningOrStop: ").append(toIndentedString(isRunningOrStop)).append("\n");
    sb.append("    challengeId: ").append(toIndentedString(challengeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

