/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * CreateRequestModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-24T12:51:03.671750900+05:30[Asia/Calcutta]")
public class CreateRequestModel implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_REQUEST_TO_USER_ID = "requestToUserId";
  @SerializedName(SERIALIZED_NAME_REQUEST_TO_USER_ID)
  private Long requestToUserId;


  public CreateRequestModel requestToUserId(Long requestToUserId) {
    
    this.requestToUserId = requestToUserId;
    return this;
  }

   /**
   * Get requestToUserId
   * @return requestToUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getRequestToUserId() {
    return requestToUserId;
  }


  public void setRequestToUserId(Long requestToUserId) {
    this.requestToUserId = requestToUserId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateRequestModel createRequestModel = (CreateRequestModel) o;
    return Objects.equals(this.requestToUserId, createRequestModel.requestToUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestToUserId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateRequestModel {\n");
    sb.append("    requestToUserId: ").append(toIndentedString(requestToUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

