/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.MethodBase;
import java.io.Serializable;

/**
 * Exception
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-06T18:15:43.848127100+05:30[Asia/Calcutta]")
public class Exception implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_TARGET_SITE = "targetSite";
  @SerializedName(SERIALIZED_NAME_TARGET_SITE)
  private MethodBase targetSite;

  public static final String SERIALIZED_NAME_STACK_TRACE = "stackTrace";
  @SerializedName(SERIALIZED_NAME_STACK_TRACE)
  private String stackTrace;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private Map<String, Object> data = null;

  public static final String SERIALIZED_NAME_INNER_EXCEPTION = "innerException";
  @SerializedName(SERIALIZED_NAME_INNER_EXCEPTION)
  private Exception innerException;

  public static final String SERIALIZED_NAME_HELP_LINK = "helpLink";
  @SerializedName(SERIALIZED_NAME_HELP_LINK)
  private String helpLink;

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  private String source;

  public static final String SERIALIZED_NAME_H_RESULT = "hResult";
  @SerializedName(SERIALIZED_NAME_H_RESULT)
  private Integer hResult;


  public Exception targetSite(MethodBase targetSite) {
    
    this.targetSite = targetSite;
    return this;
  }

   /**
   * Get targetSite
   * @return targetSite
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MethodBase getTargetSite() {
    return targetSite;
  }


  public void setTargetSite(MethodBase targetSite) {
    this.targetSite = targetSite;
  }


   /**
   * Get stackTrace
   * @return stackTrace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStackTrace() {
    return stackTrace;
  }




  public Exception message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, Object> getData() {
    return data;
  }




  public Exception innerException(Exception innerException) {
    
    this.innerException = innerException;
    return this;
  }

   /**
   * Get innerException
   * @return innerException
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Exception getInnerException() {
    return innerException;
  }


  public void setInnerException(Exception innerException) {
    this.innerException = innerException;
  }


  public Exception helpLink(String helpLink) {
    
    this.helpLink = helpLink;
    return this;
  }

   /**
   * Get helpLink
   * @return helpLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHelpLink() {
    return helpLink;
  }


  public void setHelpLink(String helpLink) {
    this.helpLink = helpLink;
  }


  public Exception source(String source) {
    
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSource() {
    return source;
  }


  public void setSource(String source) {
    this.source = source;
  }


  public Exception hResult(Integer hResult) {
    
    this.hResult = hResult;
    return this;
  }

   /**
   * Get hResult
   * @return hResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer gethResult() {
    return hResult;
  }


  public void sethResult(Integer hResult) {
    this.hResult = hResult;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Exception exception = (Exception) o;
    return Objects.equals(this.targetSite, exception.targetSite) &&
        Objects.equals(this.stackTrace, exception.stackTrace) &&
        Objects.equals(this.message, exception.message) &&
        Objects.equals(this.data, exception.data) &&
        Objects.equals(this.innerException, exception.innerException) &&
        Objects.equals(this.helpLink, exception.helpLink) &&
        Objects.equals(this.source, exception.source) &&
        Objects.equals(this.hResult, exception.hResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetSite, stackTrace, message, data, innerException, helpLink, source, hResult);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Exception {\n");
    sb.append("    targetSite: ").append(toIndentedString(targetSite)).append("\n");
    sb.append("    stackTrace: ").append(toIndentedString(stackTrace)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    innerException: ").append(toIndentedString(innerException)).append("\n");
    sb.append("    helpLink: ").append(toIndentedString(helpLink)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    hResult: ").append(toIndentedString(hResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

