/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;
import java.io.Serializable;

/**
 * GetUserGearModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-24T12:51:03.671750900+05:30[Asia/Calcutta]")
public class GetUserGearModel implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_NICK_NAME = "nickName";
  @SerializedName(SERIALIZED_NAME_NICK_NAME)
  private String nickName;

  public static final String SERIALIZED_NAME_MAX_DISTANCE = "maxDistance";
  @SerializedName(SERIALIZED_NAME_MAX_DISTANCE)
  private Long maxDistance;

  public static final String SERIALIZED_NAME_DISTANCE_MEASUREMENT_ID = "distanceMeasurementId";
  @SerializedName(SERIALIZED_NAME_DISTANCE_MEASUREMENT_ID)
  private Long distanceMeasurementId;

  public static final String SERIALIZED_NAME_IS_RETIRED = "isRetired";
  @SerializedName(SERIALIZED_NAME_IS_RETIRED)
  private Boolean isRetired;

  public static final String SERIALIZED_NAME_START_DATE = "startDate";
  @SerializedName(SERIALIZED_NAME_START_DATE)
  private Date startDate;

  public static final String SERIALIZED_NAME_GEAR_ID = "gearId";
  @SerializedName(SERIALIZED_NAME_GEAR_ID)
  private Long gearId;

  public static final String SERIALIZED_NAME_BRAND_ID = "brandId";
  @SerializedName(SERIALIZED_NAME_BRAND_ID)
  private Long brandId;

  public static final String SERIALIZED_NAME_IS_WALKING = "isWalking";
  @SerializedName(SERIALIZED_NAME_IS_WALKING)
  private Boolean isWalking;

  public static final String SERIALIZED_NAME_BRAND_NAME = "brandName";
  @SerializedName(SERIALIZED_NAME_BRAND_NAME)
  private String brandName;

  public static final String SERIALIZED_NAME_MODEL_NAME = "modelName";
  @SerializedName(SERIALIZED_NAME_MODEL_NAME)
  private String modelName;

  public static final String SERIALIZED_NAME_EXPIRY_DATE = "expiryDate";
  @SerializedName(SERIALIZED_NAME_EXPIRY_DATE)
  private Date expiryDate;

  private boolean isSelected;

  public GetUserGearModel setIsSelected(boolean isSelected)
  {
    this.isSelected = isSelected;
    return  this;
  }

  public boolean getIsSelected()
  {
    return isSelected;
  }

  public GetUserGearModel id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public GetUserGearModel nickName(String nickName) {
    
    this.nickName = nickName;
    return this;
  }

   /**
   * Get nickName
   * @return nickName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNickName() {
    return nickName;
  }


  public void setNickName(String nickName) {
    this.nickName = nickName;
  }


  public GetUserGearModel maxDistance(Long maxDistance) {
    
    this.maxDistance = maxDistance;
    return this;
  }

   /**
   * Get maxDistance
   * @return maxDistance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getMaxDistance() {
    return maxDistance;
  }


  public void setMaxDistance(Long maxDistance) {
    this.maxDistance = maxDistance;
  }


  public GetUserGearModel distanceMeasurementId(Long distanceMeasurementId) {
    
    this.distanceMeasurementId = distanceMeasurementId;
    return this;
  }

   /**
   * Get distanceMeasurementId
   * @return distanceMeasurementId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getDistanceMeasurementId() {
    return distanceMeasurementId;
  }


  public void setDistanceMeasurementId(Long distanceMeasurementId) {
    this.distanceMeasurementId = distanceMeasurementId;
  }


  public GetUserGearModel isRetired(Boolean isRetired) {
    
    this.isRetired = isRetired;
    return this;
  }

   /**
   * Get isRetired
   * @return isRetired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsRetired() {
    return isRetired;
  }


  public void setIsRetired(Boolean isRetired) {
    this.isRetired = isRetired;
  }


  public GetUserGearModel startDate(Date startDate) {
    
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Date getStartDate() {
    return startDate;
  }


  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }


  public GetUserGearModel gearId(Long gearId) {
    
    this.gearId = gearId;
    return this;
  }

   /**
   * Get gearId
   * @return gearId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getGearId() {
    return gearId;
  }


  public void setGearId(Long gearId) {
    this.gearId = gearId;
  }


  public GetUserGearModel brandId(Long brandId) {
    
    this.brandId = brandId;
    return this;
  }

   /**
   * Get brandId
   * @return brandId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getBrandId() {
    return brandId;
  }


  public void setBrandId(Long brandId) {
    this.brandId = brandId;
  }


  public GetUserGearModel isWalking(Boolean isWalking) {
    
    this.isWalking = isWalking;
    return this;
  }

   /**
   * Get isWalking
   * @return isWalking
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsWalking() {
    return isWalking;
  }


  public void setIsWalking(Boolean isWalking) {
    this.isWalking = isWalking;
  }


  public GetUserGearModel brandName(String brandName) {
    
    this.brandName = brandName;
    return this;
  }

   /**
   * Get brandName
   * @return brandName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBrandName() {
    return brandName;
  }


  public void setBrandName(String brandName) {
    this.brandName = brandName;
  }


  public GetUserGearModel modelName(String modelName) {
    
    this.modelName = modelName;
    return this;
  }

   /**
   * Get modelName
   * @return modelName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getModelName() {
    return modelName;
  }


  public void setModelName(String modelName) {
    this.modelName = modelName;
  }


  public GetUserGearModel expiryDate(Date expiryDate) {
    
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Date getExpiryDate() {
    return expiryDate;
  }


  public void setExpiryDate(Date expiryDate) {
    this.expiryDate = expiryDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetUserGearModel getUserGearModel = (GetUserGearModel) o;
    return Objects.equals(this.id, getUserGearModel.id) &&
        Objects.equals(this.nickName, getUserGearModel.nickName) &&
        Objects.equals(this.maxDistance, getUserGearModel.maxDistance) &&
        Objects.equals(this.distanceMeasurementId, getUserGearModel.distanceMeasurementId) &&
        Objects.equals(this.isRetired, getUserGearModel.isRetired) &&
        Objects.equals(this.startDate, getUserGearModel.startDate) &&
        Objects.equals(this.gearId, getUserGearModel.gearId) &&
        Objects.equals(this.brandId, getUserGearModel.brandId) &&
        Objects.equals(this.isWalking, getUserGearModel.isWalking) &&
        Objects.equals(this.brandName, getUserGearModel.brandName) &&
        Objects.equals(this.modelName, getUserGearModel.modelName) &&
        Objects.equals(this.expiryDate, getUserGearModel.expiryDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nickName, maxDistance, distanceMeasurementId, isRetired, startDate, gearId, brandId, isWalking, brandName, modelName, expiryDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUserGearModel {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nickName: ").append(toIndentedString(nickName)).append("\n");
    sb.append("    maxDistance: ").append(toIndentedString(maxDistance)).append("\n");
    sb.append("    distanceMeasurementId: ").append(toIndentedString(distanceMeasurementId)).append("\n");
    sb.append("    isRetired: ").append(toIndentedString(isRetired)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    gearId: ").append(toIndentedString(gearId)).append("\n");
    sb.append("    brandId: ").append(toIndentedString(brandId)).append("\n");
    sb.append("    isWalking: ").append(toIndentedString(isWalking)).append("\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

