/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * HeightModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-02T12:44:20.356130700+05:30[Asia/Calcutta]")
public class HeightModule implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_HEIGHT_MEASUREMENT_NAME = "heightMeasurementName";
  @SerializedName(SERIALIZED_NAME_HEIGHT_MEASUREMENT_NAME)
  private String heightMeasurementName;

  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  private String unit;


  public HeightModule id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public HeightModule heightMeasurementName(String heightMeasurementName) {
    
    this.heightMeasurementName = heightMeasurementName;
    return this;
  }

   /**
   * Get heightMeasurementName
   * @return heightMeasurementName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHeightMeasurementName() {
    return heightMeasurementName;
  }


  public void setHeightMeasurementName(String heightMeasurementName) {
    this.heightMeasurementName = heightMeasurementName;
  }


  public HeightModule unit(String unit) {
    
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUnit() {
    return unit;
  }


  public void setUnit(String unit) {
    this.unit = unit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HeightModule heightModel = (HeightModule) o;
    return Objects.equals(this.id, heightModel.id) &&
        Objects.equals(this.heightMeasurementName, heightModel.heightMeasurementName) &&
        Objects.equals(this.unit, heightModel.unit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, heightMeasurementName, unit);
  }

 /* @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HeightModel {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    heightMeasurementName: ").append(toIndentedString(heightMeasurementName)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("}");
    return sb.toString();
  }*/
 @Override
 public String toString() {
   return unit;
 }
  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

