/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.Assembly;
import org.openapitools.client.model.CustomAttributeData;
import org.openapitools.client.model.ModuleHandle;
import java.io.Serializable;

/**
 * Module
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-06T18:15:43.848127100+05:30[Asia/Calcutta]")
public class Module implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ASSEMBLY = "assembly";
  @SerializedName(SERIALIZED_NAME_ASSEMBLY)
  private Assembly assembly;

  public static final String SERIALIZED_NAME_FULLY_QUALIFIED_NAME = "fullyQualifiedName";
  @SerializedName(SERIALIZED_NAME_FULLY_QUALIFIED_NAME)
  private String fullyQualifiedName;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_MD_STREAM_VERSION = "mdStreamVersion";
  @SerializedName(SERIALIZED_NAME_MD_STREAM_VERSION)
  private Integer mdStreamVersion;

  public static final String SERIALIZED_NAME_MODULE_VERSION_ID = "moduleVersionId";
  @SerializedName(SERIALIZED_NAME_MODULE_VERSION_ID)
  private UUID moduleVersionId;

  public static final String SERIALIZED_NAME_SCOPE_NAME = "scopeName";
  @SerializedName(SERIALIZED_NAME_SCOPE_NAME)
  private String scopeName;

  public static final String SERIALIZED_NAME_MODULE_HANDLE = "moduleHandle";
  @SerializedName(SERIALIZED_NAME_MODULE_HANDLE)
  private ModuleHandle moduleHandle;

  public static final String SERIALIZED_NAME_CUSTOM_ATTRIBUTES = "customAttributes";
  @SerializedName(SERIALIZED_NAME_CUSTOM_ATTRIBUTES)
  private List<CustomAttributeData> customAttributes = null;

  public static final String SERIALIZED_NAME_METADATA_TOKEN = "metadataToken";
  @SerializedName(SERIALIZED_NAME_METADATA_TOKEN)
  private Integer metadataToken;


  public Module assembly(Assembly assembly) {
    
    this.assembly = assembly;
    return this;
  }

   /**
   * Get assembly
   * @return assembly
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Assembly getAssembly() {
    return assembly;
  }


  public void setAssembly(Assembly assembly) {
    this.assembly = assembly;
  }


   /**
   * Get fullyQualifiedName
   * @return fullyQualifiedName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFullyQualifiedName() {
    return fullyQualifiedName;
  }




   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }




   /**
   * Get mdStreamVersion
   * @return mdStreamVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMdStreamVersion() {
    return mdStreamVersion;
  }




   /**
   * Get moduleVersionId
   * @return moduleVersionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UUID getModuleVersionId() {
    return moduleVersionId;
  }




   /**
   * Get scopeName
   * @return scopeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getScopeName() {
    return scopeName;
  }




  public Module moduleHandle(ModuleHandle moduleHandle) {
    
    this.moduleHandle = moduleHandle;
    return this;
  }

   /**
   * Get moduleHandle
   * @return moduleHandle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ModuleHandle getModuleHandle() {
    return moduleHandle;
  }


  public void setModuleHandle(ModuleHandle moduleHandle) {
    this.moduleHandle = moduleHandle;
  }


   /**
   * Get customAttributes
   * @return customAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CustomAttributeData> getCustomAttributes() {
    return customAttributes;
  }




   /**
   * Get metadataToken
   * @return metadataToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMetadataToken() {
    return metadataToken;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Module module = (Module) o;
    return Objects.equals(this.assembly, module.assembly) &&
        Objects.equals(this.fullyQualifiedName, module.fullyQualifiedName) &&
        Objects.equals(this.name, module.name) &&
        Objects.equals(this.mdStreamVersion, module.mdStreamVersion) &&
        Objects.equals(this.moduleVersionId, module.moduleVersionId) &&
        Objects.equals(this.scopeName, module.scopeName) &&
        Objects.equals(this.moduleHandle, module.moduleHandle) &&
        Objects.equals(this.customAttributes, module.customAttributes) &&
        Objects.equals(this.metadataToken, module.metadataToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assembly, fullyQualifiedName, name, mdStreamVersion, moduleVersionId, scopeName, moduleHandle, customAttributes, metadataToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Module {\n");
    sb.append("    assembly: ").append(toIndentedString(assembly)).append("\n");
    sb.append("    fullyQualifiedName: ").append(toIndentedString(fullyQualifiedName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mdStreamVersion: ").append(toIndentedString(mdStreamVersion)).append("\n");
    sb.append("    moduleVersionId: ").append(toIndentedString(moduleVersionId)).append("\n");
    sb.append("    scopeName: ").append(toIndentedString(scopeName)).append("\n");
    sb.append("    moduleHandle: ").append(toIndentedString(moduleHandle)).append("\n");
    sb.append("    customAttributes: ").append(toIndentedString(customAttributes)).append("\n");
    sb.append("    metadataToken: ").append(toIndentedString(metadataToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

