/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CustomAttributeData;
import org.openapitools.client.model.MemberInfo;
import org.openapitools.client.model.ParameterAttributes;
import org.openapitools.client.model.Type;
import java.io.Serializable;

/**
 * ParameterInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-06T18:15:43.848127100+05:30[Asia/Calcutta]")
public class ParameterInfo implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private ParameterAttributes attributes;

  public static final String SERIALIZED_NAME_MEMBER = "member";
  @SerializedName(SERIALIZED_NAME_MEMBER)
  private MemberInfo member;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PARAMETER_TYPE = "parameterType";
  @SerializedName(SERIALIZED_NAME_PARAMETER_TYPE)
  private Type parameterType;

  public static final String SERIALIZED_NAME_POSITION = "position";
  @SerializedName(SERIALIZED_NAME_POSITION)
  private Integer position;

  public static final String SERIALIZED_NAME_IS_IN = "isIn";
  @SerializedName(SERIALIZED_NAME_IS_IN)
  private Boolean isIn;

  public static final String SERIALIZED_NAME_IS_LCID = "isLcid";
  @SerializedName(SERIALIZED_NAME_IS_LCID)
  private Boolean isLcid;

  public static final String SERIALIZED_NAME_IS_OPTIONAL = "isOptional";
  @SerializedName(SERIALIZED_NAME_IS_OPTIONAL)
  private Boolean isOptional;

  public static final String SERIALIZED_NAME_IS_OUT = "isOut";
  @SerializedName(SERIALIZED_NAME_IS_OUT)
  private Boolean isOut;

  public static final String SERIALIZED_NAME_IS_RETVAL = "isRetval";
  @SerializedName(SERIALIZED_NAME_IS_RETVAL)
  private Boolean isRetval;

  public static final String SERIALIZED_NAME_DEFAULT_VALUE = "defaultValue";
  @SerializedName(SERIALIZED_NAME_DEFAULT_VALUE)
  private Object defaultValue = null;

  public static final String SERIALIZED_NAME_RAW_DEFAULT_VALUE = "rawDefaultValue";
  @SerializedName(SERIALIZED_NAME_RAW_DEFAULT_VALUE)
  private Object rawDefaultValue = null;

  public static final String SERIALIZED_NAME_HAS_DEFAULT_VALUE = "hasDefaultValue";
  @SerializedName(SERIALIZED_NAME_HAS_DEFAULT_VALUE)
  private Boolean hasDefaultValue;

  public static final String SERIALIZED_NAME_CUSTOM_ATTRIBUTES = "customAttributes";
  @SerializedName(SERIALIZED_NAME_CUSTOM_ATTRIBUTES)
  private List<CustomAttributeData> customAttributes = null;

  public static final String SERIALIZED_NAME_METADATA_TOKEN = "metadataToken";
  @SerializedName(SERIALIZED_NAME_METADATA_TOKEN)
  private Integer metadataToken;


  public ParameterInfo attributes(ParameterAttributes attributes) {
    
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ParameterAttributes getAttributes() {
    return attributes;
  }


  public void setAttributes(ParameterAttributes attributes) {
    this.attributes = attributes;
  }


  public ParameterInfo member(MemberInfo member) {
    
    this.member = member;
    return this;
  }

   /**
   * Get member
   * @return member
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MemberInfo getMember() {
    return member;
  }


  public void setMember(MemberInfo member) {
    this.member = member;
  }


   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }




  public ParameterInfo parameterType(Type parameterType) {
    
    this.parameterType = parameterType;
    return this;
  }

   /**
   * Get parameterType
   * @return parameterType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Type getParameterType() {
    return parameterType;
  }


  public void setParameterType(Type parameterType) {
    this.parameterType = parameterType;
  }


   /**
   * Get position
   * @return position
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPosition() {
    return position;
  }




   /**
   * Get isIn
   * @return isIn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsIn() {
    return isIn;
  }




   /**
   * Get isLcid
   * @return isLcid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsLcid() {
    return isLcid;
  }




   /**
   * Get isOptional
   * @return isOptional
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsOptional() {
    return isOptional;
  }




   /**
   * Get isOut
   * @return isOut
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsOut() {
    return isOut;
  }




   /**
   * Get isRetval
   * @return isRetval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsRetval() {
    return isRetval;
  }




   /**
   * Get defaultValue
   * @return defaultValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getDefaultValue() {
    return defaultValue;
  }




   /**
   * Get rawDefaultValue
   * @return rawDefaultValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getRawDefaultValue() {
    return rawDefaultValue;
  }




   /**
   * Get hasDefaultValue
   * @return hasDefaultValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getHasDefaultValue() {
    return hasDefaultValue;
  }




   /**
   * Get customAttributes
   * @return customAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CustomAttributeData> getCustomAttributes() {
    return customAttributes;
  }




   /**
   * Get metadataToken
   * @return metadataToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMetadataToken() {
    return metadataToken;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParameterInfo parameterInfo = (ParameterInfo) o;
    return Objects.equals(this.attributes, parameterInfo.attributes) &&
        Objects.equals(this.member, parameterInfo.member) &&
        Objects.equals(this.name, parameterInfo.name) &&
        Objects.equals(this.parameterType, parameterInfo.parameterType) &&
        Objects.equals(this.position, parameterInfo.position) &&
        Objects.equals(this.isIn, parameterInfo.isIn) &&
        Objects.equals(this.isLcid, parameterInfo.isLcid) &&
        Objects.equals(this.isOptional, parameterInfo.isOptional) &&
        Objects.equals(this.isOut, parameterInfo.isOut) &&
        Objects.equals(this.isRetval, parameterInfo.isRetval) &&
        Objects.equals(this.defaultValue, parameterInfo.defaultValue) &&
        Objects.equals(this.rawDefaultValue, parameterInfo.rawDefaultValue) &&
        Objects.equals(this.hasDefaultValue, parameterInfo.hasDefaultValue) &&
        Objects.equals(this.customAttributes, parameterInfo.customAttributes) &&
        Objects.equals(this.metadataToken, parameterInfo.metadataToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributes, member, name, parameterType, position, isIn, isLcid, isOptional, isOut, isRetval, defaultValue, rawDefaultValue, hasDefaultValue, customAttributes, metadataToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParameterInfo {\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    member: ").append(toIndentedString(member)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parameterType: ").append(toIndentedString(parameterType)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    isIn: ").append(toIndentedString(isIn)).append("\n");
    sb.append("    isLcid: ").append(toIndentedString(isLcid)).append("\n");
    sb.append("    isOptional: ").append(toIndentedString(isOptional)).append("\n");
    sb.append("    isOut: ").append(toIndentedString(isOut)).append("\n");
    sb.append("    isRetval: ").append(toIndentedString(isRetval)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    rawDefaultValue: ").append(toIndentedString(rawDefaultValue)).append("\n");
    sb.append("    hasDefaultValue: ").append(toIndentedString(hasDefaultValue)).append("\n");
    sb.append("    customAttributes: ").append(toIndentedString(customAttributes)).append("\n");
    sb.append("    metadataToken: ").append(toIndentedString(metadataToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

