/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ParameterAttributes
 */
@JsonAdapter(ParameterAttributes.Adapter.class)
public enum ParameterAttributes {
  
  NUMBER_0(0),
  
  NUMBER_1(1),
  
  NUMBER_2(2),
  
  NUMBER_4(4),
  
  NUMBER_8(8),
  
  NUMBER_16(16),
  
  NUMBER_4096(4096),
  
  NUMBER_8192(8192),
  
  NUMBER_16384(16384),
  
  NUMBER_32768(32768),
  
  NUMBER_61440(61440);

  private Integer value;

  ParameterAttributes(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ParameterAttributes fromValue(Integer value) {
    for (ParameterAttributes b : ParameterAttributes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ParameterAttributes> {
    @Override
    public void write(final JsonWriter jsonWriter, final ParameterAttributes enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ParameterAttributes read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return ParameterAttributes.fromValue(value);
    }
  }
}

