/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * ParticipantsdetailsModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-24T12:51:03.671750900+05:30[Asia/Calcutta]")
public class ParticipantsdetailsModel implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_CHALLENGE_ID = "challengeId";
  @SerializedName(SERIALIZED_NAME_CHALLENGE_ID)
  private Long challengeId;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Long userId;

  public static final String SERIALIZED_NAME_INVITE_USER_NAME = "inviteUserName";
  @SerializedName(SERIALIZED_NAME_INVITE_USER_NAME)
  private String inviteUserName;

  public static final String SERIALIZED_NAME_INVITE_USER_CONTACT_NUMBER = "inviteUserContactNumber";
  @SerializedName(SERIALIZED_NAME_INVITE_USER_CONTACT_NUMBER)
  private String inviteUserContactNumber;

  public static final String SERIALIZED_NAME_INVITE_USER_EMAIL_ID = "inviteUserEmailId";
  @SerializedName(SERIALIZED_NAME_INVITE_USER_EMAIL_ID)
  private String inviteUserEmailId;

  public static final String SERIALIZED_NAME_INVITE_STATUS_ID = "inviteStatusId";
  @SerializedName(SERIALIZED_NAME_INVITE_STATUS_ID)
  private Long inviteStatusId;


  public ParticipantsdetailsModel challengeId(Long challengeId) {
    
    this.challengeId = challengeId;
    return this;
  }

   /**
   * Get challengeId
   * @return challengeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getChallengeId() {
    return challengeId;
  }


  public void setChallengeId(Long challengeId) {
    this.challengeId = challengeId;
  }


  public ParticipantsdetailsModel userId(Long userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getUserId() {
    return userId;
  }


  public void setUserId(Long userId) {
    this.userId = userId;
  }


  public ParticipantsdetailsModel inviteUserName(String inviteUserName) {
    
    this.inviteUserName = inviteUserName;
    return this;
  }

   /**
   * Get inviteUserName
   * @return inviteUserName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInviteUserName() {
    return inviteUserName;
  }


  public void setInviteUserName(String inviteUserName) {
    this.inviteUserName = inviteUserName;
  }


  public ParticipantsdetailsModel inviteUserContactNumber(String inviteUserContactNumber) {
    
    this.inviteUserContactNumber = inviteUserContactNumber;
    return this;
  }

   /**
   * Get inviteUserContactNumber
   * @return inviteUserContactNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInviteUserContactNumber() {
    return inviteUserContactNumber;
  }


  public void setInviteUserContactNumber(String inviteUserContactNumber) {
    this.inviteUserContactNumber = inviteUserContactNumber;
  }


  public ParticipantsdetailsModel inviteUserEmailId(String inviteUserEmailId) {
    
    this.inviteUserEmailId = inviteUserEmailId;
    return this;
  }

   /**
   * Get inviteUserEmailId
   * @return inviteUserEmailId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInviteUserEmailId() {
    return inviteUserEmailId;
  }


  public void setInviteUserEmailId(String inviteUserEmailId) {
    this.inviteUserEmailId = inviteUserEmailId;
  }


  public ParticipantsdetailsModel inviteStatusId(Long inviteStatusId) {
    
    this.inviteStatusId = inviteStatusId;
    return this;
  }

   /**
   * Get inviteStatusId
   * @return inviteStatusId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getInviteStatusId() {
    return inviteStatusId;
  }


  public void setInviteStatusId(Long inviteStatusId) {
    this.inviteStatusId = inviteStatusId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParticipantsdetailsModel participantsdetailsModel = (ParticipantsdetailsModel) o;
    return Objects.equals(this.challengeId, participantsdetailsModel.challengeId) &&
        Objects.equals(this.userId, participantsdetailsModel.userId) &&
        Objects.equals(this.inviteUserName, participantsdetailsModel.inviteUserName) &&
        Objects.equals(this.inviteUserContactNumber, participantsdetailsModel.inviteUserContactNumber) &&
        Objects.equals(this.inviteUserEmailId, participantsdetailsModel.inviteUserEmailId) &&
        Objects.equals(this.inviteStatusId, participantsdetailsModel.inviteStatusId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(challengeId, userId, inviteUserName, inviteUserContactNumber, inviteUserEmailId, inviteStatusId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParticipantsdetailsModel {\n");
    sb.append("    challengeId: ").append(toIndentedString(challengeId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    inviteUserName: ").append(toIndentedString(inviteUserName)).append("\n");
    sb.append("    inviteUserContactNumber: ").append(toIndentedString(inviteUserContactNumber)).append("\n");
    sb.append("    inviteUserEmailId: ").append(toIndentedString(inviteUserEmailId)).append("\n");
    sb.append("    inviteStatusId: ").append(toIndentedString(inviteStatusId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

