/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CustomAttributeData;
import org.openapitools.client.model.MemberTypes;
import org.openapitools.client.model.MethodInfo;
import org.openapitools.client.model.Module;
import org.openapitools.client.model.PropertyAttributes;
import org.openapitools.client.model.Type;
import java.io.Serializable;

/**
 * PropertyInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-06T18:15:43.848127100+05:30[Asia/Calcutta]")
public class PropertyInfo implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DECLARING_TYPE = "declaringType";
  @SerializedName(SERIALIZED_NAME_DECLARING_TYPE)
  private Type declaringType;

  public static final String SERIALIZED_NAME_REFLECTED_TYPE = "reflectedType";
  @SerializedName(SERIALIZED_NAME_REFLECTED_TYPE)
  private Type reflectedType;

  public static final String SERIALIZED_NAME_MODULE = "module";
  @SerializedName(SERIALIZED_NAME_MODULE)
  private Module module;

  public static final String SERIALIZED_NAME_CUSTOM_ATTRIBUTES = "customAttributes";
  @SerializedName(SERIALIZED_NAME_CUSTOM_ATTRIBUTES)
  private List<CustomAttributeData> customAttributes = null;

  public static final String SERIALIZED_NAME_IS_COLLECTIBLE = "isCollectible";
  @SerializedName(SERIALIZED_NAME_IS_COLLECTIBLE)
  private Boolean isCollectible;

  public static final String SERIALIZED_NAME_METADATA_TOKEN = "metadataToken";
  @SerializedName(SERIALIZED_NAME_METADATA_TOKEN)
  private Integer metadataToken;

  public static final String SERIALIZED_NAME_MEMBER_TYPE = "memberType";
  @SerializedName(SERIALIZED_NAME_MEMBER_TYPE)
  private MemberTypes memberType;

  public static final String SERIALIZED_NAME_PROPERTY_TYPE = "propertyType";
  @SerializedName(SERIALIZED_NAME_PROPERTY_TYPE)
  private Type propertyType;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private PropertyAttributes attributes;

  public static final String SERIALIZED_NAME_IS_SPECIAL_NAME = "isSpecialName";
  @SerializedName(SERIALIZED_NAME_IS_SPECIAL_NAME)
  private Boolean isSpecialName;

  public static final String SERIALIZED_NAME_CAN_READ = "canRead";
  @SerializedName(SERIALIZED_NAME_CAN_READ)
  private Boolean canRead;

  public static final String SERIALIZED_NAME_CAN_WRITE = "canWrite";
  @SerializedName(SERIALIZED_NAME_CAN_WRITE)
  private Boolean canWrite;

  public static final String SERIALIZED_NAME_GET_METHOD = "getMethod";
  @SerializedName(SERIALIZED_NAME_GET_METHOD)
  private MethodInfo getMethod;

  public static final String SERIALIZED_NAME_SET_METHOD = "setMethod";
  @SerializedName(SERIALIZED_NAME_SET_METHOD)
  private MethodInfo setMethod;


   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }




  public PropertyInfo declaringType(Type declaringType) {
    
    this.declaringType = declaringType;
    return this;
  }

   /**
   * Get declaringType
   * @return declaringType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Type getDeclaringType() {
    return declaringType;
  }


  public void setDeclaringType(Type declaringType) {
    this.declaringType = declaringType;
  }


  public PropertyInfo reflectedType(Type reflectedType) {
    
    this.reflectedType = reflectedType;
    return this;
  }

   /**
   * Get reflectedType
   * @return reflectedType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Type getReflectedType() {
    return reflectedType;
  }


  public void setReflectedType(Type reflectedType) {
    this.reflectedType = reflectedType;
  }


  public PropertyInfo module(Module module) {
    
    this.module = module;
    return this;
  }

   /**
   * Get module
   * @return module
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Module getModule() {
    return module;
  }


  public void setModule(Module module) {
    this.module = module;
  }


   /**
   * Get customAttributes
   * @return customAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CustomAttributeData> getCustomAttributes() {
    return customAttributes;
  }




   /**
   * Get isCollectible
   * @return isCollectible
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsCollectible() {
    return isCollectible;
  }




   /**
   * Get metadataToken
   * @return metadataToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMetadataToken() {
    return metadataToken;
  }




  public PropertyInfo memberType(MemberTypes memberType) {
    
    this.memberType = memberType;
    return this;
  }

   /**
   * Get memberType
   * @return memberType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MemberTypes getMemberType() {
    return memberType;
  }


  public void setMemberType(MemberTypes memberType) {
    this.memberType = memberType;
  }


  public PropertyInfo propertyType(Type propertyType) {
    
    this.propertyType = propertyType;
    return this;
  }

   /**
   * Get propertyType
   * @return propertyType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Type getPropertyType() {
    return propertyType;
  }


  public void setPropertyType(Type propertyType) {
    this.propertyType = propertyType;
  }


  public PropertyInfo attributes(PropertyAttributes attributes) {
    
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PropertyAttributes getAttributes() {
    return attributes;
  }


  public void setAttributes(PropertyAttributes attributes) {
    this.attributes = attributes;
  }


   /**
   * Get isSpecialName
   * @return isSpecialName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsSpecialName() {
    return isSpecialName;
  }




   /**
   * Get canRead
   * @return canRead
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getCanRead() {
    return canRead;
  }




   /**
   * Get canWrite
   * @return canWrite
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getCanWrite() {
    return canWrite;
  }




  public PropertyInfo getMethod(MethodInfo getMethod) {
    
    this.getMethod = getMethod;
    return this;
  }

   /**
   * Get getMethod
   * @return getMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MethodInfo getGetMethod() {
    return getMethod;
  }


  public void setGetMethod(MethodInfo getMethod) {
    this.getMethod = getMethod;
  }


  public PropertyInfo setMethod(MethodInfo setMethod) {
    
    this.setMethod = setMethod;
    return this;
  }

   /**
   * Get setMethod
   * @return setMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MethodInfo getSetMethod() {
    return setMethod;
  }


  public void setSetMethod(MethodInfo setMethod) {
    this.setMethod = setMethod;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropertyInfo propertyInfo = (PropertyInfo) o;
    return Objects.equals(this.name, propertyInfo.name) &&
        Objects.equals(this.declaringType, propertyInfo.declaringType) &&
        Objects.equals(this.reflectedType, propertyInfo.reflectedType) &&
        Objects.equals(this.module, propertyInfo.module) &&
        Objects.equals(this.customAttributes, propertyInfo.customAttributes) &&
        Objects.equals(this.isCollectible, propertyInfo.isCollectible) &&
        Objects.equals(this.metadataToken, propertyInfo.metadataToken) &&
        Objects.equals(this.memberType, propertyInfo.memberType) &&
        Objects.equals(this.propertyType, propertyInfo.propertyType) &&
        Objects.equals(this.attributes, propertyInfo.attributes) &&
        Objects.equals(this.isSpecialName, propertyInfo.isSpecialName) &&
        Objects.equals(this.canRead, propertyInfo.canRead) &&
        Objects.equals(this.canWrite, propertyInfo.canWrite) &&
        Objects.equals(this.getMethod, propertyInfo.getMethod) &&
        Objects.equals(this.setMethod, propertyInfo.setMethod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, declaringType, reflectedType, module, customAttributes, isCollectible, metadataToken, memberType, propertyType, attributes, isSpecialName, canRead, canWrite, getMethod, setMethod);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropertyInfo {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    declaringType: ").append(toIndentedString(declaringType)).append("\n");
    sb.append("    reflectedType: ").append(toIndentedString(reflectedType)).append("\n");
    sb.append("    module: ").append(toIndentedString(module)).append("\n");
    sb.append("    customAttributes: ").append(toIndentedString(customAttributes)).append("\n");
    sb.append("    isCollectible: ").append(toIndentedString(isCollectible)).append("\n");
    sb.append("    metadataToken: ").append(toIndentedString(metadataToken)).append("\n");
    sb.append("    memberType: ").append(toIndentedString(memberType)).append("\n");
    sb.append("    propertyType: ").append(toIndentedString(propertyType)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    isSpecialName: ").append(toIndentedString(isSpecialName)).append("\n");
    sb.append("    canRead: ").append(toIndentedString(canRead)).append("\n");
    sb.append("    canWrite: ").append(toIndentedString(canWrite)).append("\n");
    sb.append("    getMethod: ").append(toIndentedString(getMethod)).append("\n");
    sb.append("    setMethod: ").append(toIndentedString(setMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

