/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * ProvinceStateModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-24T12:51:03.671750900+05:30[Asia/Calcutta]")
public class ProvinceStateModel implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_PROVINCE_STATE_ID = "provinceStateId";
  @SerializedName(SERIALIZED_NAME_PROVINCE_STATE_ID)
  private Long provinceStateId;

  public static final String SERIALIZED_NAME_PROVINCE_STATE_NAME = "provinceStateName";
  @SerializedName(SERIALIZED_NAME_PROVINCE_STATE_NAME)
  private String provinceStateName;


  public ProvinceStateModel provinceStateId(Long provinceStateId) {
    
    this.provinceStateId = provinceStateId;
    return this;
  }

   /**
   * Get provinceStateId
   * @return provinceStateId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getProvinceStateId() {
    return provinceStateId;
  }


  public void setProvinceStateId(Long provinceStateId) {
    this.provinceStateId = provinceStateId;
  }


  public ProvinceStateModel provinceStateName(String provinceStateName) {
    
    this.provinceStateName = provinceStateName;
    return this;
  }

   /**
   * Get provinceStateName
   * @return provinceStateName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProvinceStateName() {
    return provinceStateName;
  }


  public void setProvinceStateName(String provinceStateName) {
    this.provinceStateName = provinceStateName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProvinceStateModel provinceStateModel = (ProvinceStateModel) o;
    return Objects.equals(this.provinceStateId, provinceStateModel.provinceStateId) &&
        Objects.equals(this.provinceStateName, provinceStateModel.provinceStateName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(provinceStateId, provinceStateName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProvinceStateModel {\n");
    sb.append("    provinceStateId: ").append(toIndentedString(provinceStateId)).append("\n");
    sb.append("    provinceStateName: ").append(toIndentedString(provinceStateName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

