/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * SubscriptionPlanModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-24T12:51:03.671750900+05:30[Asia/Calcutta]")
public class SubscriptionPlanModel implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_PLAN_NAME = "subscriptionPlanName";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_PLAN_NAME)
  private String subscriptionPlanName;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_AMOUNT = "subscriptionAmount";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_AMOUNT)
  private String subscriptionAmount;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_DESCRIPTION = "subscriptionDescription";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_DESCRIPTION)
  private String subscriptionDescription;


  public SubscriptionPlanModel id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public SubscriptionPlanModel subscriptionPlanName(String subscriptionPlanName) {
    
    this.subscriptionPlanName = subscriptionPlanName;
    return this;
  }

   /**
   * Get subscriptionPlanName
   * @return subscriptionPlanName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubscriptionPlanName() {
    return subscriptionPlanName;
  }


  public void setSubscriptionPlanName(String subscriptionPlanName) {
    this.subscriptionPlanName = subscriptionPlanName;
  }


  public SubscriptionPlanModel subscriptionAmount(String subscriptionAmount) {
    
    this.subscriptionAmount = subscriptionAmount;
    return this;
  }

   /**
   * Get subscriptionAmount
   * @return subscriptionAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubscriptionAmount() {
    return subscriptionAmount;
  }


  public void setSubscriptionAmount(String subscriptionAmount) {
    this.subscriptionAmount = subscriptionAmount;
  }


  public SubscriptionPlanModel subscriptionDescription(String subscriptionDescription) {
    
    this.subscriptionDescription = subscriptionDescription;
    return this;
  }

   /**
   * Get subscriptionDescription
   * @return subscriptionDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubscriptionDescription() {
    return subscriptionDescription;
  }


  public void setSubscriptionDescription(String subscriptionDescription) {
    this.subscriptionDescription = subscriptionDescription;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionPlanModel subscriptionPlanModel = (SubscriptionPlanModel) o;
    return Objects.equals(this.id, subscriptionPlanModel.id) &&
        Objects.equals(this.subscriptionPlanName, subscriptionPlanModel.subscriptionPlanName) &&
        Objects.equals(this.subscriptionAmount, subscriptionPlanModel.subscriptionAmount) &&
        Objects.equals(this.subscriptionDescription, subscriptionPlanModel.subscriptionDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, subscriptionPlanName, subscriptionAmount, subscriptionDescription);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionPlanModel {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    subscriptionPlanName: ").append(toIndentedString(subscriptionPlanName)).append("\n");
    sb.append("    subscriptionAmount: ").append(toIndentedString(subscriptionAmount)).append("\n");
    sb.append("    subscriptionDescription: ").append(toIndentedString(subscriptionDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

