/*
 * RPM Mobile
 * RPM Mobile
 *
 * The version of the OpenAPI document: Phase 1
 * Contact: karthikchiru@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * ThemesModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-24T12:51:03.671750900+05:30[Asia/Calcutta]")
public class ThemesModel implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_HASH_CODE = "hashCode";
  @SerializedName(SERIALIZED_NAME_HASH_CODE)
  private String hashCode;

  public static final String SERIALIZED_NAME_COLOUR_NAME = "colourName";
  @SerializedName(SERIALIZED_NAME_COLOUR_NAME)
  private String colourName;


  public ThemesModel id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public ThemesModel hashCode(String hashCode) {
    
    this.hashCode = hashCode;
    return this;
  }

   /**
   * Get hashCode
   * @return hashCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHashCode() {
    return hashCode;
  }


  public void setHashCode(String hashCode) {
    this.hashCode = hashCode;
  }


  public ThemesModel colourName(String colourName) {
    
    this.colourName = colourName;
    return this;
  }

   /**
   * Get colourName
   * @return colourName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getColourName() {
    return colourName;
  }


  public void setColourName(String colourName) {
    this.colourName = colourName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThemesModel themesModel = (ThemesModel) o;
    return Objects.equals(this.id, themesModel.id) &&
        Objects.equals(this.hashCode, themesModel.hashCode) &&
        Objects.equals(this.colourName, themesModel.colourName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, hashCode, colourName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThemesModel {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    hashCode: ").append(toIndentedString(hashCode)).append("\n");
    sb.append("    colourName: ").append(toIndentedString(colourName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

