name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Android App
      # You may pin to the exact commit or the version.
      # uses: sparkfabrik/android-build-action@02e36921259edb617c8395c1432b3164b3257e8e
      uses: sparkfabrik/android-build-action@v1.0.0
      with:
        # Project path
        project-path: 
        # Output path of apk
        output-path: # optional, default is output.apk
        # Name of the gradle task to exec
        gradle-task: # optional, default is assembleDebug
        # Boolean to tell the Action to upload the .ipa to Browserstack App Live after the build.
        browserstack-upload: # optional
        # Browserstack username (required if browserstack-upload == true)
        browserstack-username: # optional, default is 
        # Browserstack access key (required if browserstack-upload == true)
        browserstack-access-key: # optional, default is 
